apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab-arm64-pangarabbit.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gitlab-arm64-pangarabbit.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gitlab-arm64-pangarabbit.name" . }}
    spec:
      containers:
        - name: gitlab
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: gitlab-storage
              mountPath: /var/opt/gitlab
      volumes:
        - name: gitlab-storage
          persistentVolumeClaim:
            claimName: gitlab-pvc
      nodeSelector:
        kubernetes.io/arch: arm64
      resources:
{{- toYaml .Values.resources | nindent 12 }}
