apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ortelius
  namespace: ortelius
  finalizers:
    - resources-finalizer.argocd.argoproj.io # enabling cascading deletion
spec:
  project: pangarabbit
  source:
    repoURL: 'https://charts.lifecycle.keptn.sh' # helm chart repository
    chart: ortelius # helm chart name
    targetRevision: 0.5.1 # helm chart version - use latest available here
    helm:
      parameters:
        - name: "commitID"
          value: "$ARGOCD_APP_REVISION"
  destination:
    server: 'https://kubernetes.default.svc' # server where Keptn will be deployed
    namespace: ortelius # namespace where Ortelius will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true