apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab # The name of the Argo CD application
  namespace: gitlab # The namespace for the Argo CD application itself
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Enabling cascading deletion
  labels:
    name: gitlab # Label for the application
spec:
  project: pangarabbit # The Argo CD project to which this application belongs
  source:
    repoURL: https://charts.gitlab.io # The Helm chart repository URL
    targetRevision: 8.0.1 # The version of the Helm chart to deploy
    chart: gitlab # The Helm chart name
    helm:
      parameters:
        - name: certmanager-issuer.email # Parameter for Cert-Manager email configuration
          value: sachajw@gmail.com
        - name: global.image.registry # Docker registry for GitLab images
          value: registry.hub.docker.com/zengxs/gitlab
        - name: global.image.tag # GitLab image tag/version
          value: 17.0-ee
        - name: postgresql.image.tag # PostgreSQL image tag/version
          value: 13.6.0
  destination:
    server: https://kubernetes.default.svc # The server URL of the Kubernetes cluster
    namespace: gitlab # The namespace in the cluster where the application will be deployed
  syncPolicy:
    automated:
      prune: true # Automatically remove resources that are no longer defined in Git
      selfHeal: true # Automatically sync the application if it deviates from the desired state
    syncOptions:
      - CreateNamespace=true # Create the namespace if it does not exist
