replicaCount: 2

image:
  repository: zengxs/gitlab
  tag: 17.1-ee
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  httpsPort: 443
  sshPort: 22

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 1024Mi

gitlab:
  externalUrl: https://gitlab.pangarabbit.com
  sshPort: 22
