apiVersion: v1
entries:
  gitlab-arm64-pangarabbit:
    - apiVersion: v2
      appVersion: 1.16.0
      created: "2024-08-02T13:18:14.879442+02:00"
      description: A Helm chart for deploying Gitlab ARMv64
      digest: 05e096175fdd2cd7734466b71767b262345c727a5c90cec11daffbebdad33690
      maintainers:
        - email: sacha@pangarabbit.com
          name: sachajw
          url: https://github.com/sachajw
      name: gitlab-arm64-pangarabbit
      type: application
      urls:
        - https://github.com/sachajw/gitlab-helm-chart-pangarabbit/releases/download/0.1.0-helm/gitlab-arm64-pangarabbit-0.1.0.tgz
      version: 0.2.0
