replicaCount: 1

image:
  repository: zengxs/gitlab
  tag: v17-ce
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: gitlab.pangarabbit.com
      paths:
        - /
  tls: []
  # Example:
  # tls:
  #   - secretName: gitlab-tls
  #     hosts:
  #       - gitlab.local

storageClass:
  name:
  provisioner: kubernetes.io/no-provisioner
  volumeBindingMode: WaitForFirstConsumer

resources: {}
# Example:
# resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
